:NoRecursiveTypes
:GeneralizeCurriedFunctions
:NoConstrainedTypes
:DontDistributeForalls


// --------- //


def test (f: forall 'a. 'a -> 'a) =
  f
//│ test: (forall 'a. 'a -> 'a) -> (forall 'a. 'a -> 'a)
//│     = [Function: test]

test(f: forall 'a. 'a -> 'a) =
  f 1
//│ test: (forall 'a. 'a -> 'a) -> (1 | 'b)
//│     = [Function: test1]

test(f: forall 'a. 'a -> 'a) =
  (f 1, f true)
//│ test: (forall 'a. 'a -> 'a) -> (1 | 'b, true | 'c,)
//│     = [Function: test2]


test id
//│ res: (1, true,)
//│    = [ 1, true ]

test(fun x -> x)
//│ res: (1, true,)
//│    = [ 1, true ]

test(fun x ->
  let tmp = log x
  in x)
//│ res: (1, true,)
//│    = [ 1, true ]
//│ // Output
//│ 1
//│ true

:e
test(fun x -> x + 1)
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.44: 	test(fun x -> x + 1)
//│ ║        	^^^^^^^^^^^^^^^^^^^^
//│ ╟── type `‘a_92` is not an instance of type `int`
//│ ║  l.20: 	test(f: forall 'a. 'a -> 'a) =
//│ ║        	               ^^
//│ ╟── Note: constraint arises from reference:
//│ ║  l.44: 	test(fun x -> x + 1)
//│ ╙──      	              ^
//│ res: error
//│    = [ 2, 2 ]

:e
test succ
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.58: 	test succ
//│ ║        	^^^^^^^^^
//│ ╟── type `‘a_99` is not an instance of type `int`
//│ ║  l.20: 	test(f: forall 'a. 'a -> 'a) =
//│ ╙──      	               ^^
//│ res: error
//│    = [ 2, 2 ]


// --------- //


test f =
  ((f: forall 'a. 'a -> 'a) 1, f 2)
//│ test: (forall 'a. 2 -> 'b & 'a -> 'a & 'c) -> (1 | 'd, 'b,)
//│     = [Function: test3]

def pair x y = test id
//│ pair: 'a -> (forall 'b, 'c, 'd, 'e. 'b -> ((1 | 'c, 2 | 'd,) | 'e))
//│     = [Function: pair]

def pair x y = test (fun x -> (let tmp = log x in x))
//│ pair: 'a -> (forall 'b, 'c, 'd, 'e. 'b -> ((1 | 'c, 2 | 'd,) | 'e))
//│     = [Function: pair1]


def test f =
  pair (f 1) (f true)
//│ test: (true -> ('a & 'b) & (1 | 'c) -> ('d & 'e) & 'f) -> ((1 | 'c, 2 | 'g,) | 'h)
//│     = [Function: test4]

test id
//│ res: (1, 2,)
//│    = [ 1, 2 ]
//│ // Output
//│ 1
//│ 2

:e
test (fun x -> x + 1)
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.99: 	test (fun x -> x + 1)
//│ ║        	^^^^^^^^^^^^^^^^^^^^^
//│ ╟── reference of type `true` is not an instance of type `int`
//│ ║  l.87: 	  pair (f 1) (f true)
//│ ║        	                ^^^^
//│ ╟── Note: constraint arises from reference:
//│ ║  l.99: 	test (fun x -> x + 1)
//│ ╙──      	               ^
//│ res: error
//│    = [ 1, 2 ]
//│ // Output
//│ 1
//│ 2


